---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Create dynamic MySQL variables.
      set_fact:
        mysql_users:
          - name: mycompany_user
            host: "{{ groups['railsapp'][0] }}"
            password: secret
            priv: "*.*:SELECT"
        mysql_replication_master: "{{ groups['railsapp'][0] }}"

  roles:
    - geerlingguy.mysql
